import { describe, it, expect, beforeEach, vi } from "vitest";
import request from "supertest";

import app from "../../src/app.js";
import authService from "../../src/services/authService.js";

vi.mock("../../src/services/authService.js", () => ({
    default: {
        registerUser: vi.fn(),
        loginUser: vi.fn(),
        logoutUser: vi.fn(),
        refreshAccessToken: vi.fn(),
    },
}));

describe("POST /auth/login", () => {
    beforeEach(() => {
        vi.clearAllMocks();
    });

    it("should login successfully with valid credentials", async () => {
        authService.loginUser.mockResolvedValue({
            user: {
                userId: "STU001",
                name: "Bhaumik Modi",
                email: "bhaumik@example.com",
                role: "STUDENT",
                sem: 5,
                deptId: 101,
            },
            accessToken: "mock-access-token",
            refreshToken: "mock-refresh-token",
        });

        const response = await request(app)
            .post("/auth/login")
            .send({
                email: "bhaumik@example.com",
                password: "Password@123",
            });

        expect(response.status).toBe(200);

        expect(response.body).toEqual({
            success: true,
            message: "Login successful",
            data: {
                user: {
                    userId: "STU001",
                    name: "Bhaumik Modi",
                    email: "bhaumik@example.com",
                    role: "STUDENT",
                    sem: 5,
                    deptId: 101,
                },
                accessToken: "mock-access-token",
            },
        });

        expect(authService.loginUser).toHaveBeenCalledTimes(1);
    });

    it("should return the authenticated user and access token in the response", async () => {
        authService.loginUser.mockResolvedValue({
            user: {
                userId: "FAC001",
                name: "Faculty User",
                email: "faculty@example.com",
                role: "FACULTY",
            },
            accessToken: "faculty-access-token",
            refreshToken: "faculty-refresh-token",
        });

        const response = await request(app)
            .post("/auth/login")
            .send({
                email: "faculty@example.com",
                password: "Faculty@123",
            });

        expect(response.status).toBe(200);

        expect(response.body.success).toBe(true);
        expect(response.body.message).toBe("Login successful");

        expect(response.body.data).toHaveProperty("user");
        expect(response.body.data).toHaveProperty(
            "accessToken",
            "faculty-access-token"
        );

        expect(response.body.data.user).toEqual({
            userId: "FAC001",
            name: "Faculty User",
            email: "faculty@example.com",
            role: "FACULTY",
        });
    });

    it("should return the access token generated by the authentication service", async () => {
        authService.loginUser.mockResolvedValue({
            user: {
                userId: "STU002",
                name: "Test Student",
                email: "student@example.com",
                role: "STUDENT",
                sem: 3,
                deptId: 102,
            },
            accessToken: "unique-access-token-123",
            refreshToken: "unique-refresh-token-123",
        });

        const response = await request(app)
            .post("/auth/login")
            .send({
                email: "student@example.com",
                password: "Password@123",
            });

        expect(response.status).toBe(200);
        expect(response.body.data.accessToken).toBe(
            "unique-access-token-123"
        );
    });

    it("should set the refresh token in an HTTP-only cookie", async () => {
        authService.loginUser.mockResolvedValue({
            user: {
                userId: "STU003",
                name: "Cookie User",
                email: "cookie@example.com",
                role: "STUDENT",
                sem: 4,
                deptId: 103,
            },
            accessToken: "cookie-access-token",
            refreshToken: "cookie-refresh-token",
        });

        const response = await request(app)
            .post("/auth/login")
            .send({
                email: "cookie@example.com",
                password: "Password@123",
            });

        expect(response.status).toBe(200);

        const cookies = response.headers["set-cookie"];

        expect(cookies).toBeDefined();
        expect(cookies.length).toBeGreaterThan(0);

        const refreshCookie = cookies.find((cookie) =>
            cookie.startsWith("refreshToken=")
        );

        expect(refreshCookie).toBeDefined();
        expect(refreshCookie).toContain(
            "refreshToken=cookie-refresh-token"
        );
        expect(refreshCookie.toLowerCase()).toContain("httponly");
    });

    it("should normalize the email before passing it to the service", async () => {
        authService.loginUser.mockResolvedValue({
            user: {
                userId: "STU004",
                name: "Normalized User",
                email: "normalized@example.com",
                role: "STUDENT",
                sem: 5,
                deptId: 104,
            },
            accessToken: "normalized-access-token",
            refreshToken: "normalized-refresh-token",
        });

        const response = await request(app)
            .post("/auth/login")
            .send({
                email: "  NORMALIZED@EXAMPLE.COM  ",
                password: "Password@123",
            });

        expect(response.status).toBe(200);

        expect(authService.loginUser).toHaveBeenCalledWith(
            "normalized@example.com",
            "Password@123"
        );
    });

    it("should return 401 when the service rejects invalid credentials", async () => {
        const error = new Error("Invalid email or password");
        error.statusCode = 401;

        authService.loginUser.mockRejectedValue(error);

        const response = await request(app)
            .post("/auth/login")
            .send({
                email: "wrong@example.com",
                password: "WrongPassword@123",
            });

        expect(response.status).toBe(401);

        expect(response.body).toEqual({
            success: false,
            message: "Invalid email or password",
        });
    });

    it("should return 500 when the login service throws an unknown error", async () => {
        authService.loginUser.mockRejectedValue(
            new Error("Unexpected database failure")
        );

        const response = await request(app)
            .post("/auth/login")
            .send({
                email: "user@example.com",
                password: "Password@123",
            });

        expect(response.status).toBe(500);

        expect(response.body).toEqual({
            success: false,
            message: "Unexpected database failure",
        });
    });

    it("should pass the email and password to the authentication service", async () => {
        authService.loginUser.mockResolvedValue({
            user: {
                userId: "STU005",
                name: "Argument Test",
                email: "argument@example.com",
                role: "STUDENT",
                sem: 6,
                deptId: 105,
            },
            accessToken: "argument-access-token",
            refreshToken: "argument-refresh-token",
        });

        const response = await request(app)
            .post("/auth/login")
            .send({
                email: "argument@example.com",
                password: "Password@123",
            });

        expect(response.status).toBe(200);

        expect(authService.loginUser).toHaveBeenCalledTimes(1);

        expect(authService.loginUser).toHaveBeenCalledWith(
            "argument@example.com",
            "Password@123"
        );
    });
});
